{
 "title": "Monitoring- und Logging-Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "db",
    "label": "PostgreSQL DB",
    "query": "label_values(pg_stat_user_tables_n_tup_ins, datname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Kafka - Verfügbar",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "up{job=\"kafka\"}"
    }
   ]
  },
  {
   "title": "Spark-1 - Verfügbar",
   "type": "stat",
   "gridPos": { "x": 4, "y": 0, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "up{job=\"spark1\"}"
    }
   ]
  },
  {
   "title": "Spark-2 - Verfügbar",
   "type": "stat",
   "gridPos": { "x": 8, "y": 0, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "up{job=\"spark2\"}"
    }
   ]
  },
  {
   "title": "Spark-3 - Verfügbar",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "up{job=\"spark3\"}"
    }
   ]
  },
  {
   "title": "PostgreSQL - Verfügbar",
   "type": "stat",
   "gridPos": { "x": 16, "y": 0, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "up{job=\"postgresql\"}"
    }
   ]
  },
  {
   "title": "Prometheus - Verfügbar",
   "type": "stat",
   "gridPos": { "x": 20, "y": 0, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "up{job=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "Kafka Topic Binance.Trades - Nachrichten pro Sekunde",
   "type": "stat",
   "gridPos": { "x": 0, "y": 4, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_server_messages_in_per_sec{topic=\"binance.trades\"}"
    }
   ]
  },
  {
   "title": "Kafka Topic Binance.Ticker_1h - Nachrichten pro Sekunde",
   "type": "stat",
   "gridPos": { "x": 4, "y": 4, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_server_messages_in_per_sec{topic=\"binance.ticker_1h\"}"
    }
   ]
  },
  {
   "title": "Kafka Topic Binance.Ticker_1d - Nachrichten pro Sekunde",
   "type": "stat",
   "gridPos": { "x": 8, "y": 4, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_server_messages_in_per_sec{topic=\"binance.ticker_1d\"}"
    }
   ]
  },
  {
   "title": "PostgreSQL - Tabelle Trades - Anzahl der Tabelleneinträge",
   "type": "stat",
   "gridPos": { "x": 12, "y": 4, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_stat_user_tables_n_tup_ins{datname=\"$db\",relname=\"trades\",schemaname=\"public\"}"
    }
   ]
  },
  {
   "title": "PostgreSQL - Tabelle Ticker_1h - Anzahl der Tabelleneinträge",
   "type": "stat",
   "gridPos": { "x": 16, "y": 4, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_stat_user_tables_n_tup_ins{datname=\"$db\",relname=\"ticker_1h\",schemaname=\"public\"}"
    }
   ]
  },
  {
   "title": "PostgreSQL - Tabelle Ticker_1d - Anzahl der Tabelleneinträge",
   "type": "stat",
   "gridPos": { "x": 20, "y": 4, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_stat_user_tables_n_tup_ins{datname=\"$db\",relname=\"ticker_1d\",schemaname=\"public\"}"
    }
   ]
  },
  {
   "title": "Log-Einträge der Docker-Container",
   "type": "logs",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 13 },
   "targets": [
    {
     "expr": "{job=\"containerlogs\"}"
    }
   ]
  }
 ]
}