{
 "title": "Crypto Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "symbol", "label": "Auswahl Kryptowährung", "query": "BTCUSDT,ETHUSDT,SOLUSDT" }
  ]
 },
 "panels": [
  {
   "title": "Aktueller Kurswert (Graph)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "$" } },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(event_time / 1000) AS time, last_price AS \"Aktueller Kurswert $symbol in USD\" FROM ticker_1h WHERE symbol = '$symbol' ORDER BY time DESC LIMIT 500"
    }
   ]
  },
  {
   "title": "Aktueller Kurswert",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "$" } },
   "targets": [
    {
     "rawSql": "SELECT last_price AS value, NOW() AS time FROM ticker_1h WHERE symbol = '$symbol' ORDER BY event_time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Prozentuale Preisänderung im Vergleich zum Kurswert vor 1h ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT price_change_percent AS value, NOW() AS time FROM ticker_1h WHERE symbol = '$symbol' ORDER BY event_time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Prozentuale Preisänderung im Vergleich zum Kurswert vor 24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT price_change_percent AS value, NOW() AS time FROM ticker_1d WHERE symbol = '$symbol' ORDER BY event_time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Niedrigster Kurswert im Verlauf der letzten 24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "$" } },
   "targets": [
    {
     "rawSql": "SELECT MIN(low_price) AS value, NOW() AS time FROM ticker_1d WHERE symbol = '$symbol'"
    }
   ]
  },
  {
   "title": "Höchster Kurswert im Verlauf der letzten 24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "$" } },
   "targets": [
    {
     "rawSql": "SELECT MAX(high_price) AS value, NOW() AS time FROM ticker_1d WHERE symbol = '$symbol'"
    }
   ]
  },
  {
   "title": "Insgesamte Anzahl an Trades in den letzten 24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT total_trades AS value, NOW() AS time FROM ticker_1d WHERE symbol = '$symbol' ORDER BY event_time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Aktuelle Trades:",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(event_time / 1000) AS Timestamp, trade_id AS \"Trade ID\", price AS \"Aktueller Kurswert (USD)\", quantity AS \"Menge\", price * quantity AS \"Gesamtwert (USD)\" FROM trades WHERE symbol = '$symbol' ORDER BY Timestamp DESC LIMIT 100"
    }
   ]
  }
 ]
}